### ISSUE TITLE
Constrains with reverse_variable and forward_variable do no working as expected

### ISSUE THREAD

**Issue by MuhammedHasan** [biosustain/cameo#112]
Ubuntu 16.04
Python 3.5.2

I wrote following code

```
from cameo import models
model = models.bigg.e_coli_core

# O2t is reversible reaction
O2t = model.reactions.get_by_id('O2t')

constrain = model.solver.interface.Constraint(O2t.flux_expression, lb=30)
model.solver.add(constrain)

solution = model.solve()

print(solution.x_dict['O2t'])
```
and it return expected result as `30`

Then I changed constrain as 
`model.solver.interface.Constraint(O2t.forward_variable, lb=30)`

and it return an unexpected result as `21.799492655998755`

I confused because when I checked source code, I saw that 
`flux_expression = 1. * self.forward_variable - 1. * self.reverse_variable`  

Actually, I want to add a constraint with just reverse_variable or forward_variable without using flux_expression but it is not working. For example, I want to add constraint like `abs(reaction.flux_expression) >= 0` but abs is not linear or quadratic function; thus, I decide to use other implementation of abs as  `self.forward_variable + self.reverse_variable` but it does not work because of the reason explained above.

**Comment by phantomas1234** [comment]
In the first case you're setting `fwd_var - rev_var >= 30`. So `x_dict['O2t']` (which is the value of `fwd_var - rev_var`) is fixed to 30. In the second case you're only constraining `fwd_var` and leave `rev_var` unconstrained. If you print `model.reactions.O2t.forward_variable.primal` and `model.reactions.O2t.reverse_variable.primal` you will see that they are 30 (so the `fwd_var` is hitting the lower bound) and 8.200507344001245 respectively. 30 - 8.200507344001245 = 21.799492655998755. So the result is correct. 

Maybe to clarify a little bit further, the `fwd_var` value represents the flux in the forward direction and the `rev_var` in the reverse direction (similar to splitting up reversible reactions into two irreversible reactions). The actual metabolic rate of the reaction is `fwd_var - rev_var` which is equivalent to `reaction.flux_expression`.

Regarding what you're actually trying to achieve, I don't think it is possible to reformulate constraints like `abs(fwd_var - rev_var) >= 0` (which is equivalent to `abs(flux_expresion) >=0`) in a way that is possible to solve them with an LP solver. It is possible though to have `abs(flux_expression)` in an objective (check chapter 7 in https://download.aimms.com/aimms/download/manuals/AIMMS3_OM.pdf).

Can I ask what you're trying to achieve? I am not sure what `abs(fwd_var - rev_var) >= 0` should accomplish? Does this mean that the O2t flux should have a certain magnitude regardless of which direction (uptake or secretion)? If this is what you want then I am pretty sure that this is not possible. How about running to separate simulations? One time with `model.reactions.O2t.lower_bound = -1` (uptake) and one time with `model.reactions.O2t.upper_bound = 1` (secretion) for example?

Let us know if this does not help, then we could also discuss this over skype/google hangouts if you like.
