### ISSUE TITLE
Cobrapy and Cameo FVA results difference

### ISSUE THREAD

**Issue by MuhammedHasan** [biosustain/cameo#114]
Ubuntu 16.04
Python 3.5.2
solver: cplex

I have tried flux variability analysis with cameo and cobra. But their results are different. I report my experiment in [this notebook](https://github.com/MuhammedHasan/metabolitics/blob/master/src/notebooks/cobrapy_vs_cameo_fva_results.ipynb).

Moreover, cameo's fva runs 10 times slower in my machine as you see in the notebook. 

What is the wrong with this code?

**Comment by joaocardoso** [comment]
Hi @MuhammedHasan!

Can you run cameo method like this:

<code>cameo.flux_variability_analysis(model, fraction_of_optimum=1)</code>

It should give you the same result. We do not fix the biomass reaction to 100% by default.

I tested myself and cameo FVA is running slow. We will have a look into it ASAP.

Please let me know if it solves your problem.

**Comment by MuhammedHasan** [comment]
Thanks for your help.

**Comment by MuhammedHasan** [comment]
This issue closed because it solved but another issue is opened for performance problem #117.
