### ISSUE TITLE
Constraints with Indicator Variables

### ISSUE THREAD

**Issue by alicakmak** [biosustain/cameo#115]
Hi,
We are trying to use constraints associated with indicator variables. However, they do not seem to be providing the expected impact on the fba solutions. In the below example, we want at least one of R1 and R2 to have a flux over 10^-6. Accordingly, we created two indicator variables (one for each reaction's constraint, i.e., >= 10^6). Then, we created an additional constraint which enforces that at least one of the indicator variables should be 1. As the example run output shows, these constraints do not seem to be taken into consideration. Is this a bug, or we are somehow setting things wrong? Thanks.

Example case and its sample run output:
----------------------------------------------

from cobra.core import Model, Reaction
        from cameo.core import SolverBasedModel, Metabolite
        from cameo.core.solution import Solution
        from cameo.flux_analysis import fba
        import optlang 

        model = Model('example_model')
        r1 = Reaction('R1')
        r1.name = 'R1'
        r1.lower_bound = 0.
        r1.upper_bound = 1000.
        r1.objective_coefficient = 0.

        r2 = Reaction('R2')
        r2.name = 'R2'
        r2.lower_bound = 0.
        r2.upper_bound = 1000.
        r2.objective_coefficient = 0.

        r3 = Reaction('R3')
        r3.name = 'R3'
        r3.lower_bound = 0
        r3.upper_bound = 1000
        r3.objective_coefficient = 0

        ACP_c = Metabolite(
            'ACP_c',
            formula='C11H21N2O7PRS',
            name='acyl-carrier-protein',
            compartment='c')

        r1.add_metabolites({ACP_c: 1.0})
        r2.add_metabolites({ACP_c: 1.0})
        r3.add_metabolites({ACP_c: -1.0})

        model.add_reactions([r1, r2, r3])
        smodel = SolverBasedModel(description=model)
        #smodel.solver.interface = optlang.cplex_interface

        lb = 10 ** -6
        metabolite = ACP_c

        indicator_vars = []
        for r in metabolite.producers():
            var = smodel.solver.interface.Variable("var_%s" % r.id, type="binary")
            c = smodel.solver.interface.Constraint(r.flux_expression, lb=lb, indicator_variable=var,
                                                  active_when=1)  # When the indicator is 1, constraint is enforced)
            smodel.solver.add(c)
            indicator_vars.append(var)

        expr = sum(indicator_vars)
        c = smodel.solver.interface.Constraint(expr, lb=1, ub=len(indicator_vars))
        smodel.solver.add(c)

        df = fba(smodel)

        for r in metabolite.producers():
            print(r.id, df[r.id], r.forward_variable.primal, r.reverse_variable.primal)

        print(smodel.solution.status)
        print(smodel.solver)
        print(smodel.solver.interface)` 

Sample run output:
----------------------------------------------
R2 0.0 0.0 0.0
R1 0.0 0.0 0.0
optimal

\ENCODING=ISO-8859-1
----------------------------------------------------------------------
\Problem name: 
Ran 3 tests in 21.891s

Maximize
OK
 _240ad1f1mf55em11e6mb6came9177c3519c1#0:
Subject To
 ACP_c#0:                        R1 - R1_reverse_cda52 + R2 - R2_reverse_8c6d2
                                 - R3 + R3_reverse_5c108  = 0
 _240ad1fcmf55em11e6mae0ame9177c3519c1#1: var_R2 + var_R1
                                 - Rg_240ad1fcmf55em11e6mae0ame9177c3519c1#1
                                  = 1
 _240ad1f9mf55em11e6ma1f3me9177c3519c1#0: var_R2 = 1 -> R2 - R2_reverse_8c6d2
                                 >= 0.000001
 _240ad1fbmf55em11e6m8477me9177c3519c1#1: var_R1 = 1 -> R1 - R1_reverse_cda52
                                 >= 0.000001
Bounds
 0 <= R1 <= 1000
      R1_reverse_cda52 = 0
 0 <= R2 <= 1000
      R2_reverse_8c6d2 = 0
 0 <= R3 <= 1000
      R3_reverse_5c108 = 0
 0 <= var_R2 <= 1
 0 <= var_R1 <= 1
 0 <= Rg_240ad1fcmf55em11e6mae0ame9177c3519c1#1 <= 1
Binaries
 var_R2  var_R1 
End

<module 'optlang.cplex_interface' from 'C:\\Python35\\lib\\site-packages\\optlang\\cplex_interface.py'>

Process finished with exit code 0`

**Comment by KristianJensen** [comment]
Hi.

As far as I can see you are doing it correctly. I think the issue is that cplex's default tolerance is 1e-6, which means that with a lower bound at 1e-6, a primal value of 0 is feasible. As a test, could you try to do the same with a larger lower bound, e.g. 1 ?

The tolerance in cplex can be changed using `smodel.solver.problem.parameters.simplex.tolerance.feasibility.set(value)`

**Comment by alicakmak** [comment]
I think you are right! Changing the lower bounds to higher values now makes a visible difference. Appreciate the quick response, thanks! By the way, is there a way to check the values of variables that are decided by FBA as part of the solution?
