### ISSUE TITLE
FVA on Recon 2 takes forever when two constraints (with indicator variables) are added to the model

### ISSUE THREAD

**Issue by alicakmak** [biosustain/cameo#116]
**Run 1**: FVA on Recon 2 network with some custom objective function with no additional constraints to those already come with the model. This run takes 3-4 mins.

**Run 2**: Add the following three constraints into the above model, FVA does not finish (we stopped the run manually after 2 hours).

`c6c0326e-f909-11e6-9a45-c5832ca45183: var_PPDOx_1 = 1 -> 1e-05 <= 1.0*PPDOx - 1.0*PPDOx_reverse_c99fa
c6c1449c-f909-11e6-9249-c5832ca45183: var_PPDOy_1 = 1 -> 1e-05 <= 1.0*PPDOy - 1.0*PPDOy_reverse_a61f6
c6c1a68c-f909-11e6-9e90-c5832ca45183: 1 <= var_PPDOx_1 + var_PPDOy_1 <= 2`

Environment info:

Solver: Cplex
Python: 3.5

**Comment by phantomas1234** [comment]
Which solver are you using? Can you maybe set `model.solver.configuration.verbosity = 3` to see the output from the solver (if you're using GLPK and Jupyter notebook the output will be seen in the terminal where you started the notebook)? That might give you an idea of what is happening (might be a numerical issue).

**Comment by alicakmak** [comment]
It looks like CPLEX solver is just doing what it is supposed to do, but takes longer time. I think there is not much to do for constraints with indicator variables. Thanks for the comments.
