### ISSUE TITLE
Speed up pfba in cameo/don't make it the default method

### ISSUE THREAD

**Issue by phantomas1234** [biosustain/cameo#140]

**Comment by phantomas1234** [comment]
There is clearly something wrong here:

	In [1]: from cameo import pfba
	/Users/niso/anaconda3/envs/cameo3.4/lib/python3.4/site-packages/cobra/io/__init__.py:12: UserWarning: cobra.io.sbml requires libsbml
	  warn("cobra.io.sbml requires libsbml")
	/Users/niso/anaconda3/envs/cameo3.4/lib/python3.4/site-packages/cameo/visualization/plotting/__init__.py:52 UserWarning: Cannot import any plotting library. Please install one of 'plotly', 'bokeh' or 'ggplot' if you want to use any plotting function.

	In [2]: import cameo

	In [3]: m = cameo.models.bigg.iJO1366.copy()

	In [4]: %time sol = pfba(m)
	CPU times: user 5.59 s, sys: 41.9 ms, total: 5.63 s
	Wall time: 5.66 s

	In [5]: %time sol = pfba(m)
	CPU times: user 386 ms, sys: 2.93 ms, total: 389 ms
	Wall time: 390 ms

**Comment by KristianJensen** [comment]
This looks like a bug in optlang. The `sloppy` parameter doesn't get propagated all the way through inheritance so `_canonicalize` is called anyway. It should be easy to fix, but for some reason I can't get it to work...

**Comment by phantomas1234** [comment]
hmmm, interesting? That means that probably a lot of other code is too slow too then?

**Comment by KristianJensen** [comment]
Yes that could easily be the case. At least with cplex.

And I think I found my mistake now. I'll push a fix

**Comment by phantomas1234** [comment]
@KristianJensen is that fix already released in optlang?

**Comment by KristianJensen** [comment]
@phantomas1234 I just released it, should be available once travis has finished.
