### ISSUE TITLE
pip 10.0.3 module AttributeError when trying to import cameo 

### ISSUE THREAD

**Issue by paxelito** [biosustain/cameo#206]
Not any import function is possible due to the following error. Everything works fine with pip 9

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-c0c6c94fa5f1> in <module>()
----> 1 import cameo

~/Documents/git-projects/genome-based-models/env_fba/lib/python3.6/site-packages/cameo/__init__.py in <module>()
     85     ipython.magic("matplotlib inline")
     86 
---> 87 system_info = get_system_info()
     88 
     89 from ._version import get_versions

~/Documents/git-projects/genome-based-models/env_fba/lib/python3.6/site-packages/cameo/util.py in get_system_info()
    526     # pip freeze (adapted from http://stackoverflow.com/a/24322465/280182)
    527     package_info = list()
--> 528     for dist in pip.get_installed_distributions():
    529         req = str(dist.as_requirement())
    530         package_info.append(req)

AttributeError: module 'pip' has no attribute 'get_installed_distributions'

**Comment by Midnighter** [comment]
Thank you for reporting this issue @paxelito. It's something that we need to fix on a number of our projects (cobrapy and memote as well). I'm travelling at the moment but will get this done ASAP.

**Comment by sgalkina** [comment]
Fixed in cameo==0.11.6
