### ISSUE TITLE
OptKnock's overwrite input of exclude KO reactions

### ISSUE THREAD

**Issue by hvdinh16** [biosustain/cameo#220]
Hi,

When running OptKnock, I found that the returned solutions contained the reactions that I have excluded, passed in as optknock = OptKnock(model, fraction_of_optimum=0, exclude_reactions=rxns_excl).

I take a look at the code in cameo/cameo/strain_design/deterministic/linear_programming.py, and found that line #139 in the function _build_problem seems to overwrite the exclude_reactions input.
![image](https://user-images.githubusercontent.com/15752681/49758130-36371280-fc8c-11e8-892e-fa0b38390c7b.png)

Best,
Hoang

**Comment by hvdinh16** [comment]
This seems to fix it for
optknock = OptKnock(exclude_reactions=rxns_excl, use_nullspace_simplification=False, exclude_non_gene_reactions=False, remove_blocked=False).
![image](https://user-images.githubusercontent.com/15752681/49760486-9c269880-fc92-11e8-95d7-73f7eb22e636.png)

I have checked my optknock.y_vars and the solution no longer contained reactions from exclude_reactions list. The issue might be due to mismatch object between self._model.reactions and essential_reactions.

**Comment by phantomas1234** [comment]
@hvdinh16 thanks for reporting this. I think I just merged a fix implemented by @KristianJensen into the devel branch. Will hopefully roll out a new release soon.
