### ISSUE TITLE
AttributeError when importing cameo.flux_analysis.phenotypic_phase_plane

### ISSUE THREAD

**Issue by djinnome** [biosustain/cameo#235]
Hi folks,

When I try to do the following:

```python
from cameo.flux_analysis import phenotypic_phase_plane
```
I get the following error:
```
AttributeError: module 'pandas.io.formats.console' has no attribute 'in_ipython_frontend'
```

Update: The problem seemed to be that I installed `pandas==0.21.0` as per the instructions on the DTU Biosustain [cell factory design course setup](https://biosustain.github.io/cell-factory-design-course/setup/)

I have updated the AgileBioFoundry cell-factory-design-course conda  [`environment.yml`](https://github.com/AgileBioFoundry/2019-02.26-28-cell-factory-design-course/blob/master/environment.yml) to install a later version of pandas.

**Comment by phantomas1234** [comment]
Funny, just stumbled over the same problem with a student yesterday. I'll update the course materials.
