### ISSUE TITLE
Differential FVA has a compatibility issue

### ISSUE THREAD

**Issue by liudongliangHI** [biosustain/cameo#253]
I get a FutureWarning when using an older version of pandas, and initially I just ignored it. However, when using it on the server, I found that it is no longer available, because the new version of pandas has deprecated the groupby tuple sorting feature.
I'm not sure if this is a bug or just a version issue, but I fixed it by modifying it to a list.

```
C:\Users\liu\Anaconda3\lib\site-packages\cameo\strain_design\deterministic\flux_variability_based.py:531: FutureWarning:
Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.
C:\Users\liu\Anaconda3\lib\site-packages\cameo\strain_design\deterministic\flux_variability_based.py:482: FutureWarning:
Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.
```

```
for _, solution in solutions.groupby(['biomass', 'production'], as_index=False, sort=False):
```
```
self.groups = self.solutions.groupby(
            ['biomass', 'production'], as_index=False, sort=False
        )
```

https://pandas.pydata.org/pandas-docs/version/0.23/whatsnew.html#deprecations

Grouping by a tuple of keys now emits a FutureWarning and is deprecated. In the future, a tuple passed to 'by' will always refer to a single key that is the actual tuple, instead of treating the tuple as multiple keys. To retain the previous behavior, use a list instead of a tuple (GH18314)

**Comment by carrascomj** [comment]
Fixed in #262, thanks for pointing it out!
