### ISSUE TITLE
The difference between cameo and cobrapy

### ISSUE THREAD

**Issue by wintermute221** [biosustain/cameo#255]
Hi! I've got a very basic question hoping someone could help me sort it out. I looked through the documentation of cameo and found several main differences between cameo and cobrapy, which could be concluded as i) Solver interface, ii) Importing a model, and iii) Solving models. However, I can't say I fully understand them pratically and I wonder whether it is right if I firstly use cobrapy command to load my model and then implement FBA by cameo command.

By the way, I also noticed that in the documentation there is a label saying 'build failing' and I wonder if it means cameo is not able to use.

**Comment by bdelepine** [comment]
Hi @wintermute221,

COBRApy and cameo are two Python packages that can be used to study genome-scale metabolic models.

They are similar :

- both packages have an implementation of FBA (pFBA, FVA, reaction/gene knock-out and other basic algorithms),
- people that develop cameo also develop COBRApy,
- both are free and open-source software (different licence though)

... but also different:

- cameo is built on top of COBRApy,
- COBRApy is very well maintained by a big international community, cameo is affiliated to biosustain (DTU, Denmark) and has (at the moment and unfortunately) less active contributors,
- cameo is more oriented toward "cell-factory design", while COBRApy is more agnostic in its targeted user-base,
- cameo tried to be user-friendly for users that don't know too much about programming (see ["high-level API"](http://cameo.bio/#high-level-api-for-users)).

Anyway, you should have a look at their respective publications:

- cameo: https://pubs.acs.org/doi/10.1021/acssynbio.7b00423
- COBRApy: https://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-7-74

If you simply want to perform some FBA, I would recommend you to go with COBRApy. If you want more complex tasks and you know that those are already implemented in cameo, I would recommend you to try cameo.

You do not need to use COBRApy syntax to load models that you will use with cameo; I would recommend to load your model directly from an SBML file with the package that you intend to use ([cameo](http://cameo.bio/02-import-models.html#import-models-from-files) or [COBRApy](https://cobrapy.readthedocs.io/en/latest/io.html#SBML)).

cameo has also some great learning resources : https://biosustain.github.io/cell-factory-design-course/ and https://try.cameo.bio

Does that answer you question?

**Comment by wintermute221** [comment]
Awesome! Indeed answer all my questions. Thank you for that @bdelepine. Your explanation is very detailed and clear that I couldn't expect more. Really appreciate your time and thanks to that now I've got a better understanding of those two packages!

Yuhan
