### ISSUE TITLE
Escher widget in jupyter sometimes works sometimes not

### ISSUE THREAD

**Issue by katajar** [biosustain/cameo#275]
Hello,
I am trying to use Cameo and I noticed that sometimes Escher widget views result map and sometimes not. Here is the result when it doesn't work:
![image](https://user-images.githubusercontent.com/27952790/113677336-c13e4100-96bd-11eb-9042-f3da3b4695b9.png)
Do you have any idea why I can't see the map?

**Comment by carrascomj** [comment]
Hello!

There are two things to take into account:

* Escher API changed some time ago (fix here #272).
* If you are using jupyterlab, you need to install jupyter plugins. From #272 documentation:

    >### Working with jupyter lab
    >Both plotly and escher require additional steps to work with jupyter lab. For escher (based on [escher-readme](https://github.com/zakandrewking/escher/#jupyter-extensions)):
     >```bash
    >jupyter labextension install @jupyter-widgets/jupyterlab-manager
   > python -m jupyter labextension install escher
    >````
This will be added to the next version as soon as it is reviewed.

**Comment by katajar** [comment]
Thank you so much for the fast answer! 
Installation of Jupyter plugins fixed my issue but previously I needed to downgrade nodejs to 12 version (I'm using conda environment). I'll let you know when the same problem will reappear another time.
