### ISSUE TITLE
problems with exclude_reactions in OptKnock

### ISSUE THREAD

**Issue by jose-vindel** [biosustain/cameo#277]
Hello, I am trying to run OptKnock as part of the research I am conducting. One of the first steps is to understand OptKnock. When passing an argument in exclude_reactions I tried with a list with the reactions' id. First, I tried with a list of strings but I got a ValueError: Excluded reaction (reaction id) is not in the model. Then I tried to pass a list with the reaction objects. However, it seems it's not working either. This is what I did

```
from cameo.strain_design.deterministic.linear_programming import OptKnock
from cameo import models

kn = [1287,1291,1451,2062,2074,1216,2412,1318,2064,2067,1092,2239,1626,2077,614,2278,480,1243,2065,1445,2225,2224,2378,234,2382,1165,1143,2371,577,530,531,1575,877,1754,1757,1759,436] # index of reactions I want to include in the knockout search space

model = models.bigg.iJO1366

ess = [] # list of reaction objects

for index, reaction in enumerate(model.reactions):
   if index not in kn:
      ess.append(reaction)

model.solver="gurobi"
optnock = OptKnock(model,exclude_reactions = essential ,fraction_of_optimum=0.1)
result = optnock.run(max_knockouts=2, target="EX_succ_e", biomass="BIOMASS_Ec_iJO1366_core_53p95M",max_results=5)

 ```
is there something I am not doing correctly when passing that list of reaction objects? I'd appreciate the help

**Comment by carrascomj** [comment]
Blocked reactions are removed from the temporal LP model before applying the `exclude_reactions`. Can you instantiate the `OptKnock` object with an argument `remove_blocked=False` and see if that solves it?

I believe that this behavior is anti-intuitive and removed blocked reactions and excluded reactions should not clash like that, I don't know what others think.

**Comment by jose-vindel** [comment]
Thanks a lot! it solved it, one other question is there a way, besides trying to pass a list of reactions to exclude, reactions to include in the knockout list?

**Comment by carrascomj** [comment]
No, I don't think there is a way, but you can work around it:

```python
included_reactions = {r_A, r_B}  # some reactions you want to include
excluded_reactions = [reac for reac in model.reactions if reac not in included_reactions]
optnock = OptKnock(model, exclude_reactions=excluded_reactions)
```

**Comment by jose-vindel** [comment]
I'll try that thanks
