### ISSUE TITLE
Error raised in the use of different strain design algorithms of Cameo. 

### ISSUE THREAD

**Issue by Priyachan** [biosustain/cameo#279]
Hi, 
I am facing difficulties in using some of the strain design algorithms (FSEOF, differential FVA, cofactor swap)  which were previously working fine and gave results. 
I am not able to figure out what might be the issue. Please find the error below.

**Comment by Priyachan** [comment]
`ParseException Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pkg_resources_vendor\packaging\requirements.py in init(self, requirement_string)
92 try:
---> 93 req = REQUIREMENT.parseString(requirement_string)
94 except ParseException as e:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in parseString(self, instring, parseAll)
1653 # catch and re-raise exception from here, clears out pyparsing internal stack trace
-> 1654 raise exc
1655 else:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in parseString(self, instring, parseAll)
1643 try:
-> 1644 loc, tokens = self._parse( instring, 0 )
1645 if parseAll:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
1401 try:
-> 1402 loc,tokens = self.parseImpl( instring, preloc, doActions )
1403 except IndexError:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in parseImpl(self, instring, loc, doActions)
3416 else:
-> 3417 loc, exprtokens = e._parse( instring, loc, doActions )
3418 if exprtokens or exprtokens.haskeys():

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
1401 try:
-> 1402 loc,tokens = self.parseImpl( instring, preloc, doActions )
1403 except IndexError:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in parseImpl(self, instring, loc, doActions)
3738 if self.expr is not None:
-> 3739 return self.expr._parse( instring, loc, doActions, callPreParse=False )
3740 else:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
1401 try:
-> 1402 loc,tokens = self.parseImpl( instring, preloc, doActions )
1403 except IndexError:

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in parseImpl(self, instring, loc, doActions)
3399 # pre-parsed the string as part of our And pre-parsing
-> 3400 loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
3401 errorStop = False

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
1405 else:
-> 1406 loc,tokens = self.parseImpl( instring, preloc, doActions )
1407

~\Anaconda3\lib\site-packages\pkg_resources_vendor\pyparsing.py in parseImpl(self, instring, loc, doActions)
2710 if not result:
-> 2711 raise ParseException(instring, loc, self.errmsg, self)
2712

ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

InvalidRequirement Traceback (most recent call last)
in
----> 1 from cameo import models
2 from cameo.api import design
3 from cameo.strain_design.heuristic.evolutionary.optimization import CofactorSwapOptimization
4 from cameo.strain_design.heuristic.evolutionary.objective_functions import product_yield
5 from cameo.strain_design.heuristic.evolutionary.objective_functions import biomass_product_coupled_yield

~\Anaconda3\lib\site-packages\cameo_init_.py in
85 ipython.magic("matplotlib inline")
86
---> 87 system_info = get_system_info()
88
89 from ._version import get_versions

~\Anaconda3\lib\site-packages\cameo\util.py in get_system_info()
526 package_info = list()
527 for dist in pkg_resources.working_set:
--> 528 req = str(dist.as_requirement())
529 package_info.append(req)
530 return dict(package_info=package_info,

~\Anaconda3\lib\site-packages\pkg_resources_init_.py in as_requirement(self)
2852 spec = "%s===%s" % (self.project_name, self.parsed_version)
2853
-> 2854 return Requirement.parse(spec)
2855
2856 def load_entry_point(self, group, name):

~\Anaconda3\lib\site-packages\pkg_resources_init_.py in parse(s)
3151 @staticmethod
3152 def parse(s):
-> 3153 req, = parse_requirements(s)
3154 return req
3155

~\Anaconda3\lib\site-packages\pkg_resources_init_.py in parse_requirements(strs)
3096 except StopIteration:
3097 return
-> 3098 yield Requirement(line)
3099
3100

~\Anaconda3\lib\site-packages\pkg_resources_init_.py in init(self, requirement_string)
3106 def init(self, requirement_string):
3107 """DO NOT CALL THIS UNDOCUMENTED METHOD; use Requirement.parse()!"""
-> 3108 super(Requirement, self).init(requirement_string)
3109 self.unsafe_name = self.name
3110 project_name = safe_name(self.name)

~\Anaconda3\lib\site-packages\pkg_resources_vendor\packaging\requirements.py in init(self, requirement_string)
93 req = REQUIREMENT.parseString(requirement_string)
94 except ParseException as e:
---> 95 raise InvalidRequirement(
96 'Parse error at "{0!r}": {1}'.format(
97 requirement_string[e.loc : e.loc + 8], e.msg

InvalidRequirement: Parse error at "'-ython-l'": Expected W:(abcd...)`

**Comment by paucaro2** [comment]
Hi!
I have the same error with cameo
"InvalidRequirement: Parse error at "'-ython-l'": Expected W:(abcd...)"

Did you fix it?

Ty
