### ISSUE TITLE
"TypeError: plot() missing 1 required positional argument: 'plotter'"

### ISSUE THREAD

**Issue by BeeAnka** [biosustain/cameo#283]
Hi,

I was following your tutorial (https://cameo.bio/04-analyze-models.html#). 
However whenever I want to use the plot() functions as described I get this error message: 
"TypeError: plot() missing 1 required positional argument: 'plotter'"

For example if I want to run these lines - everything works fine expect the plot():

from cameo import phenotypic_phase_plane
model.reactions.EX_o2_e.lower_bound = -10
result = phenotypic_phase_plane(model,
                                variables=[model.reactions.BIOMASS_Ecoli_core_w_GAM],
                                objective=model.reactions.EX_succ_e,
                                points=10)
result.plot()

What does "plotter" in this context mean? Any ideas how I could get plot() working? It's the actual reason why I'm using cameo, so it would be great to get it working.

**Comment by BeeAnka** [comment]
I found the solution online in this jupyter notebook  
(https://notebooks.gesis.org/binder/jupyter/user/biosustain-cameo-notebooks-gkanfhes/lab/tree/04-analyze-models.ipynb):

plotter = PlotlyPlotter()
result.plot(plotter)

Maybe update the other homepage as this notebook was not easy to find.

**Comment by carrascomj** [comment]
Hello!

Yes, that's correct.

The API changed and the updated documentation is already commited, it will be uploaded with the next release, sorry about that.
