### ISSUE TITLE
Release packages on pypi

### ISSUE THREAD

**Issue by matthiaskoenig** [biosustain/cameo#286]
It would be great if the releases could be on pypi, i.e. 0.13.3.
I currently have to do things such as
```
cameo @ git+https://github.com/biosustain/cameo/@286ea9782fa6a4374a1f2b53f037b91b2995a739#egg=cameo
```
which takes very long in CI and docker builds.

**Comment by carrascomj** [comment]
Twine has been failing on release for some reason:
* Failed deployment https://github.com/biosustain/cameo/runs/3806873572?check_suite_focus=true 
* _Possible_ fix in progress https://github.com/biosustain/cameo/pull/285

**Comment by phantomas1234** [comment]
@matthiaskoenig took some effort to fix some deployment issues to pypi that started at some point. 0.13.5 is availab now  on https://pypi.org/project/cameo/
