### ISSUE TITLE
try.cameo.bio broken

### ISSUE THREAD

**Issue by jhgorse** [biosustain/cameo#293]
Tried to go to https://try.cameo.bio
which leads to:
https://mybinder.org/v2/gh/biosustain/cameo-notebooks/binder?urlpath=lab/tree/index.ipynb

Then we see:
![image](https://user-images.githubusercontent.com/1783474/152094805-1f4cfe20-52a5-42c2-9f5a-1297f9b68ad2.png)

```
Error loading biosustain/cameo-notebooks/binder!
See logs below for details.

Your session is taking longer than usual to start!
Check the log messages below to see what is happening.
```

**Comment by carrascomj** [comment]
Ups, the badge and the route need to be updated, sorry. They are pointing to a branch at `biosustain/cameo-notebooks` that was merged into master and does not exist anymore.

It is now https://mybinder.org/v2/gh/biosustain/cameo-notebooks/master?urlpath=lab/tree/index.ipynb if you want to use it.

**Comment by jhgorse** [comment]
Works now. Cheers!
