### ISSUE TITLE
 cannot import name 'find_gene_knockout_reactions'

### ISSUE THREAD

**Issue by jetu20** [biosustain/cameo#297]
Hi I am trying to to run following command from tutorial but it gives me following error.......any suggestion to solve it

from cameo.strain_design import OptGene
![image](https://user-images.githubusercontent.com/105390844/189195273-fc544fc0-cf82-4a6b-85a1-c1e8b5a52f40.png)

ImportError: cannot import name 'find_gene_knockout_reactions' from 'cobra.manipulation.delete' (C:\Users\jetu20\Anaconda3\envs\GEM-CAMEO\lib\site-packages\cobra\manipulation\delete.py)

**Comment by carrascomj** [comment]
It seems like `find_gene_knockout_reactions` has been removed from [`cobra.manipulation.delete`](https://cobrapy.readthedocs.io/en/latest/autoapi/cobra/manipulation/delete/index.html). 

You can try downgrading cobrapy to a lower version. If you are using pip:

```bash
pip install cobra==0.20.0 --upgrade
```

But it may cause problems with libSBML, depending on your python version. Cameo should probably pin cobra to avoid this kind of issues.

**Comment by jetu20** [comment]
thanks @carrascomj  for your suggestion and it solve the issues
