### ISSUE TITLE
RuntimeError removing metabolites with destructive method

### ISSUE THREAD

**Issue by bruno2git** [biosustain/cameo#66]
A `RuntimeError: Set changed size during iteration` is thrown when removing a metabolite with `method="destructive"`.
This was tested in a Windows 10 OS, inside a Conda Python=3.4.5 environment, with the devel branch of Cameo.
A minimal example is provided in the attachment:
[minimal_example.zip](https://github.com/biosustain/cameo/files/485567/minimal_example.zip)

**Comment by hredestig** [comment]
Apologies for the extremely late feedback but this is fixed in cameo devel
`met.remove_from_model(destructive=True)`
