### ISSUE TITLE
Cameo crashes after COBRApy import on macOS

### ISSUE THREAD

**Issue by zakandrewking** [biosustain/cameo#81]
Here is a minimal script to cause a crash on my machine. The crash only occurs if cameo is imported after cobra.

``` python
# system_profiler SPSoftwareDataType
# > Software:
# >
# > System Software Overview:
# >
# > System Version: macOS 10.12 (16A323)
# > Kernel Version: Darwin 16.0.0

# brew list glpk
# > /usr/local/Cellar/glpk/4.60/bin/glpsol
# > /usr/local/Cellar/glpk/4.60/include/glpk.h
# > /usr/local/Cellar/glpk/4.60/lib/libglpk.40.dylib
# > /usr/local/Cellar/glpk/4.60/lib/ (2 other files)

import cobra
print(cobra.__version__)
# > 0.5.2

import cameo
print(cameo.__version__)
# > 0.7.1

model = cameo.models.bigg.iJO1366
# > GLPK initialization failed
# > [1]    77230 abort      python3 cobrapy_cameo_crash.py
```

**Comment by phantomas1234** [comment]
I can reproduce this. We'll try to figure out what is causing it. Thanks for the report.

**Comment by phantomas1234** [comment]
Ok, I narrowed it down to the cobrapy cglpk interface that probably does something fishy that `glp_init_env` in http://www.fon.hum.uva.nl/rob/PraatDemoApps/PraatDemoApp_module/praat_sources/external/glpk/glpenv01.c doesn't like. Not looking forward to diving into the C code.

**Comment by hredestig** [comment]
I note that this doesn't happen with glpk compiled from source.. it also only happens with the mac wheels so I deleted those from pypi. Perhaps you can try re-install cobra 0.5.2 to confirm that the problem doesn't happen with source dist.

**Comment by zakandrewking** [comment]
I no longer see the error with the latest cobra (0.5.4) downloaded from source

**Comment by hredestig** [comment]
great, the good pypi folks have fixed the wheel creation so I could now build mac wheels again where at least I don't see the issue anymore, new wheel can be tested with, perhaps you can verify that as well
 
```
pip install cobra==0.5.4.post6 -i https://testpypi.python.org/pypi
```

**Comment by zakandrewking** [comment]
I'm still seeing the error.

```
zakbook ~/Downloads $ python3 test.py
0.5.4.post6
0.7.1
GLPK initialization failed
[1]    6906 abort      python3 test.py
```

**Comment by hredestig** [comment]
ouch yes, I see had non-brew glpk installed, removing that I also get the bug again. Surprising interference there given that the wheel cobra should only use it's own dylib file :/

Since the current plan is to switch cobra over to optlang anyway I suggest we just skip cobra wheels for mac *sigh* ..unless someone would know a quick fix

**Comment by hredestig** [comment]
Version 1.4.1 of swiglpk fixes this for me @zakandrewking can you verify?

**Comment by zakandrewking** [comment]
Yup, works great :)
